routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Auth::routes([
    'register'  => false,     // Registration Routes...
    'verify'    => true,       // Email Verification Routes...
    'reset'     => true,        // Password Reset Routes...
]);

Route::group( [
    'prefix'    => 'admin',
    'as'        => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'verified', 'admin']
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    // Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    // Route::resource('permissions', 'PermissionsController');

    // // Roles
    // Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    // Route::resource('roles', 'RolesController');

    // // Users
    // Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    // Route::resource('users', 'UsersController');

    // Authors
    Route::resource('authors', 'AuthorsController');

    // Categories
    Route::resource('categories', 'CategoriesController');

    // Menu
    Route::resource('menus', 'MenusController');

    // Tags
    Route::resource('tags', 'TagsController');

    // Posts
    Route::get('posts/{post}/comments', 'PostsController@comments')->name('posts.comments');
    Route::resource('posts', 'PostsController');

    // Posts
    Route::resource('comments', 'CommentsController');

    // Pages
    Route::resource('pages', 'PagesController');

    // Contacts
    Route::get('get-contacts', 'ContactController@getContacts')->name('contacts.get');
    Route::resource('contacts', 'ContactController');

    // Blogs
    // Route::get('get-blogs', 'BlogsController@getBlogs')->name('blogs.get');
    // Route::resource('blogs', 'BlogsController');

    // Setting
    Route::resource('setting', 'WebSettingController');

    // Main Page
    Route::resource('main-page', 'MainPageController');

});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

// Route::get('/artisan-run', 'Web\PagesController@cache');

Route::group([
    'prefix'        => LaravelLocalization::setLocale(),
    'middleware'    => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ],
    'namespace'     => 'Web'
], function() {

    Route::get('/search',                       'PagesController@search')->name('search');

    Route::get('/',                             'PagesController@index')->name('home');

    Route::post('/',                            'PostsController@loadMore')->name('post.load');

    Route::get('/{slug}',                       'PostsController@index')->name('post.index');

    Route::get('/{category}/{author}/{title}',   'PostsController@show')->name('post.show');

    Route::get('/{category}/{author}/{title}',   'PostsController@show')->name('post.show');
    
    Route::post('/comment/reply',                'CommentsController@store')->name('comments.store');

});

app/WebSetting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class WebSetting extends Model
{
    use HasTranslations;

    protected $guarded = ['id'];

    public $timestamps = false;

    public $translatable  = ['section_a'];

    protected $fillable = [
        'id',
        'name',
        'email',
        'contact_show',
        'contact',
        'address',
        'facebook_link',
        'instagram_link',
        'twitter_link',
        'linkedin_link',
        'youtube_link',
        'whatsapp_link',
    ];

    public function section_a()
    {
        return $this->belongsToMany(Category::class, 'category_post' , 'post_id' , 'category_id');
    }
}

app/Http/Controllers/Admin/WebSettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\WebSetting;
use Illuminate\Http\Request;

class WebSettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $setting = WebSetting::firstOrFail();

        // return $setting;

        return view('admin.web-setting.index', compact('setting'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $setting = WebSetting::firstOrFail();
        // return $setting;
        return view('admin.web-setting.edit', compact('setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          // return $request->all();
          $setting = WebSetting::findOrFail($id);

          $request->is_blogs_offers == "on" ? $request->merge(['is_blogs_offers' => true]) : $request->merge(['is_blogs_offers' => false]);
          $request->is_services_offers == "on" ? $request->merge(['is_services_offers' => true]) : $request->merge(['is_services_offers' => false]);

          $setting->update($request->all());

          return redirect()->route('admin.setting.index');

    }
}

resources/views/admin/web-setting/edit.blade.php
@extends('layouts.admin')
@section('content')

    <main id="main" class="main">

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                            @include('partials.backend.addAndBackBtns', [
                                "page_name" => trans('cruds.setting.title_singular'),
                                'back_link' => route('admin.setting.index')
                            ])

                            <form method="POST" action="{{ route("admin.setting.update", [$setting->id]) }}" enctype="multipart/form-data">
                                @csrf
                                @method('put')
                                <div class="mb-3">
                                    <label class="required" for="name">{{ trans('cruds.setting.fields.name') }}</label>
                                    <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $setting->name) }}" required>
                                    @if($errors->has('name'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('name') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="email">{{ trans('cruds.setting.fields.email') }}</label>
                                    <input class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" type="email" name="email" id="email" value="{{ old('email', $setting->email) }}" required>
                                    @if($errors->has('email'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('email') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="contact_show">Contact Show</label>
                                    <input class="form-control {{ $errors->has('contact_show') ? 'is-invalid' : '' }}" type="text" name="contact_show" id="contact_show" value="{{ old('contact_show', $setting->contact_show) }}" required>
                                    @if($errors->has('contact_show'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('contact_show') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="contact">{{ trans('cruds.setting.fields.contact') }}</label>
                                    <input class="form-control {{ $errors->has('contact') ? 'is-invalid' : '' }}" type="text" name="contact" id="contact" value="{{ old('contact', $setting->contact) }}" required>
                                    @if($errors->has('contact'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('contact') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="address">{{ trans('cruds.setting.fields.address') }}</label>
                                    <input class="form-control {{ $errors->has('address') ? 'is-invalid' : '' }}" type="text" name="address" id="address" value="{{ old('address', $setting->address) }}" >
                                    @if($errors->has('address'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('address') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="facebook_link">{{ trans('cruds.setting.fields.facebook_link') }}</label>
                                    <input class="form-control {{ $errors->has('facebook_link') ? 'is-invalid' : '' }}" type="text" name="facebook_link" id="facebook_link" value="{{ old('facebook_link', $setting->facebook_link) }}" >
                                    @if($errors->has('facebook_link'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('facebook_link') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="instagram_link">{{ trans('cruds.setting.fields.instagram_link') }}</label>
                                    <input class="form-control {{ $errors->has('instagram_link') ? 'is-invalid' : '' }}" type="text" name="instagram_link" id="instagram_link" value="{{ old('instagram_link', $setting->instagram_link) }}" >
                                    @if($errors->has('instagram_link'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('instagram_link') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="twitter_link">Twitter Link</label>
                                    <input class="form-control {{ $errors->has('twitter_link') ? 'is-invalid' : '' }}" type="text" name="twitter_link" id="twitter_link" value="{{ old('twitter_link', $setting->twitter_link) }}" >
                                    @if($errors->has('twitter_link'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('twitter_link') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="linkedin_link">{{ trans('cruds.setting.fields.linkedin_link') }}</label>
                                    <input class="form-control {{ $errors->has('linkedin_link') ? 'is-invalid' : '' }}" type="text" name="linkedin_link" id="linkedin_link" value="{{ old('linkedin_link', $setting->linkedin_link) }}" >
                                    @if($errors->has('linkedin_link'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('linkedin_link') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="mb-3">
                                    <label class="required" for="whatsapp_link">{{ trans('cruds.setting.fields.whatsapp_link') }}</label>
                                    <input class="form-control {{ $errors->has('whatsapp_link') ? 'is-invalid' : '' }}" type="text" name="whatsapp_link" id="whatsapp_link" value="{{ old('whatsapp_link', $setting->whatsapp_link) }}" >
                                    @if($errors->has('whatsapp_link'))
                                        <div class="invalid-feedback">
                                            {{ $errors->first('whatsapp_link') }}
                                        </div>
                                    @endif
                                </div>
                                <div class="form-check form-switch mb-3">
                                    <input class="form-check-input" type="checkbox" name="is_blogs_offers" id="is_blogs_offers" {{ old('is_blogs_offers', $setting->is_blogs_offers) ? 'checked' : '' }} />
                                    <label class="form-check-label" for="is_blogs_offers">Is Blogs Offer ?</label>
                                </div>

                                <div class="form-check form-switch mb-3">
                                    <input class="form-check-input" type="checkbox" name="is_services_offers" id="is_services_offers" {{ old('is_services_offers', $setting->is_services_offers) ? 'checked' : '' }}/>
                                    <label class="form-check-label" for="is_services_offers">Is Services Offer ?</label>
                                </div>

                                <div class="mb-3">
                                    <button class="btn btn-danger" type="submit">
                                        {{ trans('global.save') }}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main><!-- End #main -->
@endsection

resources/views/admin/web-setting/index.blade.php
@extends('layouts.admin')
@section('content')

    <main id="main" class="main">
        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                            <div class="d-flex justify-content-between">
                                <h5 class="card-title">{{ trans('cruds.setting.title') }}</h5>
                                    <a href="{{ route('admin.setting.edit', $setting->id) }}" class="btn btn-sm btn-info my-auto"> {{ trans('global.edit') }} {{ trans('cruds.setting.title_singular') }} </a>
                            </div>
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.name') }}
                                        </th>
                                        <td>
                                            {{ $setting->name ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.email') }}
                                        </th>
                                        <td>
                                            {{ $setting->email ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.contact') }}
                                        </th>
                                        <td>
                                            {{ $setting->contact ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            Contact Show
                                        </th>
                                        <td>
                                            {{ $setting->contact_show ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.address') }}
                                        </th>
                                        <td>
                                            {{ $setting->address ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.facebook_link') }}
                                        </th>
                                        <td>
                                            {{ $setting->facebook_link ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.instagram_link') }}
                                        </th>
                                        <td>
                                            {{ $setting->instagram_link ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            Twitter Link
                                        </th>
                                        <td>
                                            {{ $setting->twitter_link ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.linkedin_link') }}
                                        </th>
                                        <td>
                                            {{ $setting->linkedin_link ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.whatsapp_link') }}
                                        </th>
                                        <td>
                                            {{ $setting->whatsapp_link ?? '-' }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.is_blogs_offers') }}
                                        </th>
                                        <td>
                                            @if ($setting->is_blogs_offers)
                                                <span class="badge bg-success p-2 ms-2">{{ 'Offers' }}</span>
                                            @else
                                                <span class="badge bg-danger p-2 ms-2">{{ 'Not Offer' }}</span>
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            {{ trans('cruds.setting.fields.is_services_offers') }}
                                        </th>
                                        <td>
                                            @if ($setting->is_services_offers)
                                                <span class="badge bg-success p-2 ms-2">{{ 'Offers' }}</span>
                                            @else
                                                <span class="badge bg-danger p-2 ms-2">{{ 'Not Offer' }}</span>
                                            @endif
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main><!-- End #main -->

@endsection