routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Auth::routes([
    'register'  => false,     // Registration Routes...
    'verify'    => true,       // Email Verification Routes...
    'reset'     => true,        // Password Reset Routes...
]);

Route::group( [
    'prefix'    => 'admin',
    'as'        => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'verified', 'admin']
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    // Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    // Route::resource('permissions', 'PermissionsController');

    // // Roles
    // Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    // Route::resource('roles', 'RolesController');

    // // Users
    // Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    // Route::resource('users', 'UsersController');

    // Authors
    Route::resource('authors', 'AuthorsController');

    // Categories
    Route::resource('categories', 'CategoriesController');

    // Menu
    Route::resource('menus', 'MenusController');

    // Tags
    Route::resource('tags', 'TagsController');

    // Posts
    Route::get('posts/{post}/comments', 'PostsController@comments')->name('posts.comments');
    Route::resource('posts', 'PostsController');

    // Posts
    Route::resource('comments', 'CommentsController');

    // Pages
    Route::resource('pages', 'PagesController');

    // Contacts
    Route::get('get-contacts', 'ContactController@getContacts')->name('contacts.get');
    Route::resource('contacts', 'ContactController');

    // Blogs
    // Route::get('get-blogs', 'BlogsController@getBlogs')->name('blogs.get');
    // Route::resource('blogs', 'BlogsController');

    // Setting
    Route::resource('setting', 'WebSettingController');

    // Main Page
    Route::resource('main-page', 'MainPageController');

});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

// Route::get('/artisan-run', 'Web\PagesController@cache');

Route::group([
    'prefix'        => LaravelLocalization::setLocale(),
    'middleware'    => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ],
    'namespace'     => 'Web'
], function() {

    Route::get('/search',                       'PagesController@search')->name('search');

    Route::get('/',                             'PagesController@index')->name('home');

    Route::post('/',                            'PostsController@loadMore')->name('post.load');

    Route::get('/{slug}',                       'PostsController@index')->name('post.index');

    Route::get('/{category}/{author}/{title}',   'PostsController@show')->name('post.show');

    Route::get('/{category}/{author}/{title}',   'PostsController@show')->name('post.show');
    
    Route::post('/comment/reply',                'CommentsController@store')->name('comments.store');

});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Comment extends Model 
{
    use HasTranslations;

    protected $guarded = ['id'];

    public $incrementing = true;

    public $translatable = ['name', 'comment'];

    protected $fillable = [
        'name',
        'email',
        'comment',
        'post_id',
        'avatar_id',
        'avatar_id',
        'is_approve',
    ];
    
    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
    
    public function avatar()
    {
        return $this->belongsTo(Avatar::class);
    }
    
}

app/Http/Controllers/Admin/CommentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Comment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    public function index(Request $requeset)
    {
        return Comment::all();

        return view('admin.comments.index');
    }
}

app/Http/Controllers/Web/CommentsController.php
<?php

namespace App\Http\Controllers\Web;

use App\Comment;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCommentRequest;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    public function store(StoreCommentRequest $request)
    {        
        // return $request->all();
        
        Comment::create($request->all());
        
        return redirect()->back()->withSuccess('IT WORKS!');
    }
}

resources/views/admin/comments/create.blade.php
@extends('layouts.admin')

@section('styles')

@endsection
@section('content')

    @include('partials.backend.admin-breadcrum')

    <div class="card">
        <div class="card-header">
            {{ trans('global.create') }}
        </div>

        <div class="card-body">
            <form method="POST" action="{{ route("admin.comments.store") }}" enctype="multipart/form-data">
                @csrf
                @foreach(config('translatable.locales') as $locale)

                    <div class="form-group">
                        <label class="required" for="title_{{ $locale }}">Name ({{ strtoupper($locale) }}) </label>
                        <input type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" name="title[{{ $locale }}]" id="title_{{ $locale }}" value="{{ old($locale . '.title', '') }}" >

                        @if($errors->has('*.title'))
                            <p class="text-danger">{{ $errors->first($locale.'.title') }}</p>
                        @endif
                    </div>

                    <div class="form-group">
                        <label class="required" for="info_{{ $locale }}">Info ({{ strtoupper($locale) }}) </label>
                        <textarea rows="2" class="form-control {{ $errors->has('info') ? 'is-invalid' : '' }}" name="info[{{ $locale }}]" id="info_{{ $locale }}">{{ old($locale . '.info', '') }}</textarea>

                        @if($errors->has('*.info'))
                            <p class="text-danger">{{ $errors->first($locale.'.info') }}</p>
                        @endif
                    </div>

                @endforeach

                <div class="form-group">
                    <button class="btn btn-danger" type="submit">
                        {{ trans('global.save') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
    <style>
        .ck-editor__editable_inline {
            min-height: 380px;
        }
    </style>
@endsection

@section('scripts')
    <script>
         $(document).ready(function() {

            $(".get-slug").on("change", function() {
                const slug = $(this).val().toLowerCase()
                            .trim()
                            .replace(/[^\w\s-]/g, '')
                            .replace(/[\s_-]+/g, '-')
                            .replace(/^-+|-+$/g, '');

                $('#slug').val(slug);
                $('#canonical').val('{{ config('app.url') }}' +slug);
            });

        });
    </script>
@endsection

resources/views/admin/comments/edit.blade.php
@extends('layouts.admin')

@section('styles')

@endsection
@section('content')

    @include('partials.backend.admin-breadcrum')

    <div class="card">
        <div class="card-header">
            {{ trans('global.edit') }}
        </div>

        <div class="card-body">
            <form method="POST" action="{{ route("admin.comments.update", $author->id) }}" enctype="multipart/form-data">
                @csrf
                @method('put')
                @foreach(config('translatable.locales') as $locale)
                    <div class="form-group">
                        <label class="required" for="title_{{ $locale }}">Name ({{ strtoupper($locale) }}) </label>
                        <input type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" name="title[{{ $locale }}]" id="title_{{ $locale }}" value="{{ old($locale . '.title', $author->getTranslation('title', $locale)) }}" >

                        @if($errors->has('*.title'))
                            <p class="text-danger">{{ $errors->first($locale.'.title') }}</p>
                        @endif
                    </div>

                    <div class="form-group">
                        <label class="required" for="info_{{ $locale }}">Info ({{ strtoupper($locale) }}) </label>
                        <textarea rows="2" class="form-control {{ $errors->has('info') ? 'is-invalid' : '' }}" name="info[{{ $locale }}]" id="info_{{ $locale }}">{{ old($locale . '.info', $author->getTranslation('info', $locale)) }}</textarea>

                        @if($errors->has('*.info'))
                            <p class="text-danger">{{ $errors->first($locale.'.info') }}</p>
                        @endif
                    </div>

                @endforeach

                <div class="form-group">
                    <button class="btn btn-danger" type="submit">
                        {{ trans('global.save') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
    <style>
        .ck-editor__editable_inline {
            min-height: 380px;
        }
    </style>
@endsection

@section('scripts')
    <script>
         $(document).ready(function() {

            $(".get-slug").on("change", function() {
                const slug = $(this).val().toLowerCase()
                            .trim()
                            .replace(/[^\w\s-]/g, '')
                            .replace(/[\s_-]+/g, '-')
                            .replace(/^-+|-+$/g, '');

                $('#slug').val(slug);
                $('#canonical').val('{{ config('app.url') }}' +slug);
            });

        });
    </script>
@endsection

resources/views/admin/comments/index.blade.php
@extends('layouts.admin')
@section('content')

    @include('partials.backend.admin-breadcrum')

    <!-- Main content -->
    <div id="" class="content" >
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header d-flex justify-content-between p-0 ">
                            <ul class="nav nav-pills p-2 ml-auto">
                                <a class="nav-link {{ request()->routeIs('admin.comments.index')  ? 'active' : '' }}" href="{{ route('admin.comments.create') }}">
                                    Add Author
                                </a>
                            </ul>
                        </div>
                        <div class="card-body table-responsive">
                            <table id="data-table" class="table table-striped table-hover datatable">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Name (ar)</th>
                                        <th>Name (en)</th>
                                        <th>Name (de)</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($comments as $key => $author)
                                        <tr>
                                            <td>{{ $key + 1 }}</td>
                                            <td> {{ $author->getTranslation('name', 'ar') ?? '-' }} </td>
                                            <td> {{ $author->getTranslation('name', 'en') ?? '-' }} </td>
                                            <td> {{ $author->getTranslation('name', 'de') ?? '-' }} </td>
                                            <td>
                                                <div class="btn-group btn-group-sm" role="group" aria-label="Action group">
                                                    {{-- <a href="{{ route('admin.comments.show', $author->id) }}" class="btn btn-success"><i class="fa fa-eye"></i></a> --}}

                                                    <a href="{{ route('admin.comments.edit', $author->id) }}" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                    <form id="form-delete" action="{{route('admin.comments.destroy', $author->id)}}" method="POST" onsubmit="return confirm('Posts/Blogs related to this author will also be deleted.')">
                                                        @method('delete')
                                                        @csrf
                                                        <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                                    </form>

                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
       </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

@endsection
@section('scripts')
    @parent
    {{-- <script>
        $( document ).ready(function() {
            $('#data-table').DataTable( {
                "serverSide" : false,
                "processing" : true,
                'language': {
                    'loadingRecords': '&nbsp;',
                    'processing': 'Loading...'
                },
                "order": [4, 'desc' ],
                "pageLength": 10,
                "ajax"       : {
                    "headers"    : {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                    },
                    'url' : ('{{route('admin.comments.get')}}').replace('&amp;', '&'),
                    'dataSrc':""
                },
                "columns"   : [
                    {
                        "data": "name",
                    },
                    {
                        "data": "slug",
                    },
                    {
                        "data": "canonical",
                        "render": function (data, type, row) {
                            return '<a href="'+data+'" target="_blank">'+data+'</a>';
                        }
                    },
                    {
                        "data": "is_published",
                        "render": function (data, type, row) {
                            return data ? '<span class="badge badge-success">Publish</span>' : '<span class="badge badge-danger">Not Publish</span>';
                        }
                    },
                    {
                        "data": 'slug',
                        "render": function (data, type, row) {

                            var html =  '<div class="btn-group" role="group">';
                                html += '    <a href="'+('{{route('services.show', ':slug')}}').replace(':slug', data)+'" target="_blank" class="btn btn-sm btn-success"><i class="fa fa-eye"></i></a>';
                                html += '    <a href="'+('{{route('admin.comments.edit', ':slug')}}').replace(':slug', data)+'" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a>';
                                html += '    <form action="'+('{{route('admin.comments.destroy', ':slug')}}').replace(':slug', data)+'" method="POST" onsubmit="return confirm('+'Are you sure'+');">';
                                html += '       <input type="hidden" name="_method" value="DELETE">';
                                html += '       <input type="hidden" name="_token" value="{{ csrf_token() }}">';
                                html += '       <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>';
                                html += '   </form>';
                                html += '</div>';

                            return html;
                        }
                    },
                ],
            });

            $(function() {
                let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)

                $.extend(true, $.fn.dataTable.defaults, {
                    orderCellsTop: true,
                });

                $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e) {
                    $($.fn.dataTable.tables(true)).DataTable()
                        .columns.adjust();
                });
            })
        });
    </script> --}}
@endsection