routes/web.php
<?php

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Auth::routes([
    'register'  => false,     // Registration Routes...
    'verify'    => true,       // Email Verification Routes...
    'reset'     => true,        // Password Reset Routes...
]);

Route::group( [
    'prefix'    => 'admin',
    'as'        => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'verified', 'admin']
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    // Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    // Route::resource('permissions', 'PermissionsController');

    // // Roles
    // Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    // Route::resource('roles', 'RolesController');

    // // Users
    // Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    // Route::resource('users', 'UsersController');

    // Authors
    Route::resource('authors', 'AuthorsController');

    // Categories
    Route::resource('categories', 'CategoriesController');

    // Menu
    Route::resource('menus', 'MenusController');

    // Tags
    Route::resource('tags', 'TagsController');

    // Posts
    Route::get('posts/{post}/comments', 'PostsController@comments')->name('posts.comments');
    Route::resource('posts', 'PostsController');

    // Posts
    Route::resource('comments', 'CommentsController');

    // Pages
    Route::resource('pages', 'PagesController');

    // Contacts
    Route::get('get-contacts', 'ContactController@getContacts')->name('contacts.get');
    Route::resource('contacts', 'ContactController');

    // Blogs
    // Route::get('get-blogs', 'BlogsController@getBlogs')->name('blogs.get');
    // Route::resource('blogs', 'BlogsController');

    // Setting
    Route::resource('setting', 'WebSettingController');

    // Main Page
    Route::resource('main-page', 'MainPageController');

});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

// Route::get('/artisan-run', 'Web\PagesController@cache');

Route::group([
    'prefix'        => LaravelLocalization::setLocale(),
    'middleware'    => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ],
    'namespace'     => 'Web'
], function() {

    Route::get('/search',                       'PagesController@search')->name('search');

    Route::get('/',                             'PagesController@index')->name('home');

    Route::post('/',                            'PostsController@loadMore')->name('post.load');

    Route::get('/{slug}',                       'PostsController@index')->name('post.index');

    Route::get('/{category}/{author}/{title}',   'PostsController@show')->name('post.show');

    Route::get('/{category}/{author}/{title}',   'PostsController@show')->name('post.show');
    
    Route::post('/comment/reply',                'CommentsController@store')->name('comments.store');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;
use Spatie\Sluggable\HasTranslatableSlug;
use Spatie\Sluggable\SlugOptions;

class Category extends Model
{
    use HasTranslations, HasTranslatableSlug;

    protected $guarded = ['id'];

    public $timestamps = false;

    public $translatable  = ['title', 'slug', 'color_code'];

    protected $fillable  = ['title', 'slug', 'color_code'];

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::createWithLocales( config('translatable.locales') )
            ->generateSlugsFrom(function($model, $locale) {
                return "{$model->title}";
            })
            ->saveSlugsTo('slug')
            ->usingLanguage(false);
    }

     /**
     * Get the route key for the model.
     *
     * @return string
     */
    // public function getRouteKeyName()
    // {
    //     return 'slug';
    // }

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }


    public function category()
    {
        return $this->first();
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Color;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategoryRequest;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories = Category::all();

        return view('admin.categories.index', compact('categories'));
    }

    public function create()
    {
        $colors = Color::all();

        return view('admin.categories.create', compact('colors'));
    }

    public function store(StoreCategoryRequest $request)
    {
        return $request->all();

        return Category::create($request->all());

        // Category::create($request->all());

        return redirect()->route('admin.categories.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('styles')

@endsection
@section('content')

    @include('partials.backend.admin-breadcrum')

    <div class="card">
        <div class="card-header">
            {{ trans('global.create') }}
        </div>

        <div class="card-body">
            <form method="POST" action="{{ route("admin.categories.store") }}" enctype="multipart/form-data">
                @csrf

                @foreach(config('translatable.locales') as $locale)

                    <div class="form-group">
                        <label class="required" for="title_{{ $locale }}">Title ({{ strtoupper($locale) }}) </label>
                        <input type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" name="title[{{ $locale }}]" id="title_{{ $locale }}" value="{{ old($locale . '.title', '') }}" >

                        @if($errors->has('*.title'))
                            <p class="text-danger">{{ $errors->first($locale.'.title') }}</p>
                        @endif
                    </div>

                    {{-- <div class="form-group">
                        <label class="required" for="color_code_{{ $locale }}">Color</label>
                        <select class="form-control select {{ $errors->has('color_code') ? 'is-invalid' : '' }}" name="{{ $locale }}[color_code]" id="color_code" required>
                            @foreach($colors as $id => $color)
                                <option value="{{$color->code }}" class="text-light" style="background-color: {{ $color->code }};" {{ old($locale .'.color_code', '') ? 'selected' : '' }}>
                                    {{ $color->name }}
                                </option>
                            @endforeach
                        </select>
                        @if($errors->has('color_code'))
                            <span class="text-danger">{{ $errors->first('color_code') }}</span>
                        @endif
                    </div> --}}

                @endforeach

                <div class="form-group">
                    <button class="btn btn-danger" type="submit">
                        {{ trans('global.save') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('styles')
    <style>
        #upload {
            opacity: 0;
        }

        #upload-label {
            position: absolute;
            top: 50%;
            left: 1rem;
            transform: translateY(-50%);
        }

        .image-area {
            border: 2px dashed rgba(255, 255, 255, 0.7);
            padding: 1rem;
            position: relative;
        }

        .image-area::before {
            content: 'Uploaded image result';
            color: #fff;
            font-weight: bold;
            text-transform: uppercase;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 0.8rem;
            z-index: 1;
        }

        .image-area img {
            z-index: 2;
            position: relative;
        }
    </style>
@endsection
@section('content')

    @include('partials.backend.admin-breadcrum')

    <div class="card">
        <div class="card-header">
            {{ trans('global.edit') }}
        </div>

        <div class="card-body">
            <form method="POST" action="{{ route("admin.blogs.update", [$blog->slug]) }}" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="form-group">
                    <label class="required" for="title">Title</label>
                    <input class="get-slug form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', $blog->title) }}" >
                    @if($errors->has('title'))
                        <div class="invalid-feedback">
                            {{ $errors->first('title') }}
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label class="required" for="slug">Slug</label>
                    <input class="get-slug form-control {{ $errors->has('slug') ? 'is-invalid' : '' }}" type="text" name="slug" id="slug" value="{{ old('slug', $blog->slug) }}" >
                    @if($errors->has('slug'))
                        <div class="invalid-feedback">
                            {{ $errors->first('slug') }}
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label class="required" for="canonical">Canonical</label> <small>(change <b>Title</b> or <b>Slug</b> value)</small>
                    <input class="form-control {{ $errors->has('canonical') ? 'is-invalid' : '' }}" type="url" readonly name="canonical" id="canonical" value="{{ old('canonical', $blog->canonical) }}" >
                    @if($errors->has('canonical'))
                        <div class="invalid-feedback">
                            {{ $errors->first('canonical') }}
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label class="" for="meta_description">Meta Description</label>
                    <textarea name="meta_description" id="meta_description" rows="2" style="min-height: auto" class="form-control {{ $errors->has('meta_description') ? 'is-invalid' : '' }}">{{ old('meta_description', $blog->meta_description) }}</textarea>
                    @if($errors->has('meta_description'))
                        <div class="invalid-feedback">
                            {{ $errors->first('meta_description') }}
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label class="required" for="category_id">Category</label>
                    <select class="form-control {{ $errors->has('category_id') ? 'is-invalid' : '' }}" name="category_id" id="category_id" required>
                        <option disabled hidden selected> Choose any option </option>
                        @foreach($categories as $id => $category)
                            <option {{ old('category_id', $blog->category_id) == $category->id ? "selected" : "" }} value="{{ $category->id }}" >{{ $category->name }}</option>
                        @endforeach
                    </select>
                    @if($errors->has('category_id'))
                        <div class="invalid-feedback">
                            {{ $errors->first('category_id') }}
                        </div>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('tags') ? 'has-error' : '' }}">
                    <label for="tag">Tags <small>(press <b>Ctrl</b> to select multiple)</small></label>
                    <select name="tags[]" id="tags" class="form-control {{ $errors->has('tags') ? 'is-invalid' : '' }}" multiple="multiple">
                        @foreach ($tags as $key => $tag)
                            <option  {{ (in_array($key, old('tags', [])) || $blog->tags->contains($key)) ? 'selected' : '' }}  value="{{ $tag->id }}" >{{ $tag->name }}</option>
                        @endforeach
                    </select>
                    @if($errors->has('tags'))
                        <em class="invalid-feedback">
                            {{ $errors->first('tags') }}
                        </em>
                    @endif
                </div>
                <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                    <label class="required" for="image">Image</label>
                </div>
                <div class="form-group row py-4 bg-dark">
                    <div class="col-lg-6 mx-auto">
                        <!-- Upload image input-->
                        <div class="input-group mb-3 px-2 py-2 rounded-pill {{ $errors->has('image') ? 'bg-danger' : 'bg-white' }}  shadow-sm">
                            <input id="upload" name="image" type="file" onchange="readURL(this);" class="form-control border-0">
                            <label id="upload-label" for="upload" class="font-weight-light {{ $errors->has('image') ? 'text-white' : 'text-muted' }}">Choose file</label>
                            <div class="input-group-append">
                                <label for="upload" class="btn btn-light m-0 rounded-pill px-4"><i class="fa fa-cloud-upload mr-2 text-muted"></i><small class="text-uppercase font-weight-bold text-muted ">Choose file</small></label>
                            </div>
                        </div>
                        @if ($errors->has('image'))
                            <p class="text-danger text-center">{{ $errors->first('image') }}</p>
                        @else
                            <p class="font-italic text-white text-center">The image uploaded will be rendered inside the box below.</p>
                        @endif
                        <!-- Uploaded image area-->
                        <div class="image-area mt-4"><img id="imageResult" src="{{ URL('storage/'. $blog->image_path) }}" alt="" class="img-fluid rounded shadow-sm mx-auto d-block"></div>
                    </div>
                </div>
                <div class="form-group">
                    <textarea class="ckeditor form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" rows="10" id="editor" name="description">{{ old('description', $blog->description)}}</textarea>
                    @if($errors->has('description'))
                        <div class="invalid-feedback">
                            {{ $errors->first('description') }}
                        </div>
                    @endif
                </div>

                <div class="form-check form-switch form-group">
                    <input class="form-check-input" type="checkbox" name="is_published" id="is_published" {{ $blog->is_published ? 'checked' : '' }} />
                    <label class="form-check-label" for="is_published">Publish</label>
                </div>

                <div class="form-group">
                    <button class="btn btn-danger" type="submit">
                        {{ trans('global.save') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
    <style>
        .ck-editor__editable_inline {
            min-height: 380px;
        }
    </style>
@endsection

@section('scripts')
    <script>
         $(document).ready(function() {
            /*  ==========================================
                SHOW UPLOADED IMAGE
            * ========================================== */
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#imageResult')
                            .attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }

            $(function () {
                $('#upload').on('change', function () {
                    readURL(input);
                });
            });
            /*  ==========================================
                SHOW UPLOADED IMAGE NAME
            * ========================================== */
            var input = document.getElementById( 'upload' );
            var infoArea = document.getElementById( 'upload-label' );

            input.addEventListener( 'change', showFileName );
            function showFileName( event ) {
                var input = event.srcElement;
                var fileName = input.files[0].name;
                infoArea.textContent = 'File name: ' + fileName;
            }

            $('#canonical').val('{{ $blog->canonical ?? '' }}');

            $(".get-slug").on("change", function() {
                const slug = $(this).val().toLowerCase()
                            .trim()
                            .replace(/[^\w\s-]/g, '')
                            .replace(/[\s_-]+/g, '-')
                            .replace(/^-+|-+$/g, '');

                $('#slug').val(slug);
                $('#canonical').val('{{ config('app.url') }}' +slug);
            });
        });
    </script>
    <script src="https://cdn.ckeditor.com/ckeditor5/31.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
        .create( document.querySelector( '#editor' ), {
                heading: {
                    options: [
                        { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
                        { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
                        { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
                        { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading2' },
                        { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading2' }
                    ]
                }
            })
            .then( editor => {
                // console.log( editor );
            })
            .catch( error => {
                console.error( error );
        });
    </script>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')
@section('content')

    @include('partials.backend.admin-breadcrum')

    <!-- Main content -->
    <div id="" class="content" >
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header d-flex justify-content-between p-0 ">
                            <ul class="nav nav-pills p-2 ml-auto">
                                <a class="nav-link {{ request()->routeIs('admin.categories.index')  ? 'active' : '' }}" href="{{ route('admin.categories.create') }}">
                                    Add Category
                                </a>
                            </ul>
                        </div>
                        <div class="card-body table-responsive">
                            <table id="data-table" class="table table-striped table-hover datatable">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Title (ar)</th>
                                        <th>Title (en)</th>
                                        <th>Title (de)</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($categories as $key => $category)
                                        <tr>
                                            <td>{{ $key + 1 }}</td>
                                            <td>{{ $category->getTranslation('title', 'ar') ?? '-' }}</td>
                                            <td>{{ $category->getTranslation('title', 'en') ?? '-' }}</td>
                                            <td>{{ $category->getTranslation('title', 'de') ?? '-' }}</td>
                                            <td>
                                                <div class="btn-group btn-group-sm" role="group" aria-label="Action group">
                                                    <a href="#" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                    <form id="form-delete" action="#" method="POST" onsubmit="return confirm('Posts/Blogs related to this categories will also be deleted.')">
                                                        @method('delete')
                                                        @csrf
                                                        <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
       </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

@endsection
@section('scripts')
    @parent
    {{-- <script>
        $( document ).ready(function() {
            $('#data-table').DataTable( {
                "serverSide" : false,
                "processing" : true,
                'language': {
                    'loadingRecords': '&nbsp;',
                    'processing': 'Loading...'
                },
                "order": [4, 'desc' ],
                "pageLength": 10,
                "ajax"       : {
                    "headers"    : {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                    },
                    'url' : ('{{route('admin.categories.get')}}').replace('&amp;', '&'),
                    'dataSrc':""
                },
                "columns"   : [
                    {
                        "data": "title",
                    },
                    {
                        "data": "slug",
                    },
                    {
                        "data": "canonical",
                        "render": function (data, type, row) {
                            return '<a href="'+data+'" target="_blank">'+data+'</a>';
                        }
                    },
                    {
                        "data": "is_published",
                        "render": function (data, type, row) {
                            return data ? '<span class="badge badge-success">Publish</span>' : '<span class="badge badge-danger">Not Publish</span>';
                        }
                    },
                    {
                        "data": 'slug',
                        "render": function (data, type, row) {

                            var html =  '<div class="btn-group" role="group">';
                                html += '    <a href="'+('{{route('services.show', ':slug')}}').replace(':slug', data)+'" target="_blank" class="btn btn-sm btn-success"><i class="fa fa-eye"></i></a>';
                                html += '    <a href="'+('{{route('admin.categories.edit', ':slug')}}').replace(':slug', data)+'" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a>';
                                html += '    <form action="'+('{{route('admin.categories.destroy', ':slug')}}').replace(':slug', data)+'" method="POST" onsubmit="return confirm('+'Are you sure'+');">';
                                html += '       <input type="hidden" name="_method" value="DELETE">';
                                html += '       <input type="hidden" name="_token" value="{{ csrf_token() }}">';
                                html += '       <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>';
                                html += '   </form>';
                                html += '</div>';

                            return html;
                        }
                    },
                ],
            });

            $(function() {
                let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)

                $.extend(true, $.fn.dataTable.defaults, {
                    orderCellsTop: true,
                });

                $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e) {
                    $($.fn.dataTable.tables(true)).DataTable()
                        .columns.adjust();
                });
            })
        });
    </script> --}}
@endsection